### ISSUE TITLE
Non-numeric xyValueLabels?

### ISSUE THREAD

**Issue by mark0100** [stla/graph3d#1]
Is there a way to get non-numeric xyValueLabels with graph3d?

For example if i have a data.frame with rownames how do i get these rownames as xValueLabel? The following code example does not show a graph:
```

> r2
                        R2 y x
VIX           0.0003406668 1 1
VIXRQBIN265   0.0096873516 1 2
VIXRQBIN265LH 0.0090800962 1 3
>
graph3d(r2, z=~R2, type = "bar", tooltip = TRUE, xlab = "factor", zlab = "R2", xStep=1, yStep=1, xValueLabel=JS("function(){return (rownames(r2))}"))
```

**Comment by stla** [comment]
Hi,

This should be a JavaScript function, not a R function. You can try:

```js
function(x) { 
  var label;
  switch(x) {
  case 1:
    label = "VIX";
    break;
  case 2:
    label = "VIXRQPIN265";
    break;
  case 3:
    label = "VIX.....";
  }
  return label;
}
```

In one line:

```js
function(x){var label;switch(x){case 1:label="VIX";break;case 2:label="VIXRQPIN265";break;case 3:label="VIX......"}return label}
```

**Comment by mark0100** [comment]
Hi stla,

Thanks for the example. Yes that works.

But is there no way to pass R variables to the function instead of the x, y and z -axis numerical values?

Kind regards,

Mark.

**Comment by stla** [comment]
No way I think.

**Comment by mark0100** [comment]
Ah too bad. But thank you anyway stla.
