### ISSUE TITLE
Change surfaceColors

### ISSUE THREAD

**Issue by yvonneyangyy** [stla/graph3d#2]
Hi, I would like to change the surface colors of the 3d histogram (since we are visualizing MRI values). However, only the default colors are visualized

graph3d(
  df2,
  ~x, ~y, ~MRI,
  type = "bar",
  surfaceColors =c("#4D4D4D", "#888888", "#AEAEAE", "#CCCCCC", "#E6E6E6"))
![image](https://github.com/stla/graph3d/assets/130645764/a5e74037-f0f8-4355-9fcb-40916f5b9cd9)

How can I change the surface colors?
Thanks in advance!

**Comment by stla** [comment]
Hi, 

`surfaceColors` is for surface plots. For a histogram, you can use `type = "bar-color"` and define the styles (one color per bar) in a list column of the dataframe, e.g. a column named `style`, and then you have to tell `graph3d` that you want to use this column with the help of the `style` argument. Example:

```r
library(graph3d)

dat <- data.frame(
  x = c(1,1,2,2), 
  y = c(1,2,1,2), 
  z = c(1,2,3,4)
)

dat$style <- I(list(
  list(fill = "red",    stroke = "black"),
  list(fill = "green",  stroke = "tomato"),
  list(fill = "blue",   stroke = "crimson"),
  list(fill = "orange", stroke = "darkred")
))

graph3d(
  dat, 
  type = "bar-color", 
  style = ~style, 
  zMin = 0, 
  tooltip = TRUE
)
```

![graph3d_bar-color](https://github.com/stla/graph3d/assets/4466543/d41ab2e2-604e-42f5-9193-d63244152ece)

**Comment by yvonneyangyy** [comment]
Thanks so much!
